version: "3"
services:
  fpm:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    env_file: .env
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
        - 'MYSQL_ROOT_PASSWORD=secret'
        - 'MYSQL_DATABASE=testwork'
    ports:
      - 3306:3306