version: "3"
services:
#  nginx:
#    image: nginx
#    container_name: nginx
#    restart: always
#    volumes:
#      - ./frontend/dist/frontend:/usr/share/nginx/html
#      - ./api/:/var/www/html
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8085:80
#    links:
#      - fpm
  fpm:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    env_file: .env
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
        - 'MYSQL_ROOT_PASSWORD=secret'
        - 'MYSQL_DATABASE=testwork'
    ports:
      - 3306:3306